apiVersion: v1
kind: ConfigMap
metadata:
  name: istory-app-config
data:
  application.yml: |
    spring:
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update # create | create-drop | update | validate | none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        defer-datasource-initialization: true
      datasource:
        url: jdbc:postgresql://192.168.0.2:5432/postgresdb
        username: postgres
        password: admin123
    jwt:
      issuer: dangtong@gmail.com
      secret_key: study-springboot