apiVersion: v1
kind: Secret
metadata:
  name: istory-db-secret
type: Opaque
data:
  MYSQL_DATABASE: aXN0b3J5Cg==
  MYSQL_USER: ZGFuZ3RvbmcK
  MYSQL_PASSWORD: YWRtaW4xMjMK
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjMK