apiVersion: v1
kind: ConfigMap
metadata:
  name: istory-app-config
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/istory
        username: root
        password: admin123
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
          ddl-auto: update
        show-sql: true
      application:
        name: USER-SERVICE
      jwt:
        issuer: dangtong@gmail.com
        secret_key: study-springboot